export type PortRow = { port: number; proto: "TCP" | "UDP" | "both"; name: string; note: string };

export const COMMON_PORTS: PortRow[] = [
  { port: 20, proto: "TCP", name: "FTP-DATA", note: "FTP active mode data" },
  { port: 21, proto: "TCP", name: "FTP", note: "FTP control" },
  { port: 22, proto: "TCP", name: "SSH", note: "Secure shell / SFTP" },
  { port: 23, proto: "TCP", name: "Telnet", note: "Legacy remote terminal (unencrypted)" },
  { port: 25, proto: "TCP", name: "SMTP", note: "Mail transfer (MTA)" },
  { port: 53, proto: "both", name: "DNS", note: "Domain name system" },
  { port: 67, proto: "UDP", name: "DHCP server", note: "Bootstrap server" },
  { port: 68, proto: "UDP", name: "DHCP client", note: "Bootstrap client" },
  { port: 69, proto: "UDP", name: "TFTP", note: "Trivial FTP" },
  { port: 80, proto: "TCP", name: "HTTP", note: "Web (cleartext)" },
  { port: 110, proto: "TCP", name: "POP3", note: "Mail retrieval" },
  { port: 123, proto: "UDP", name: "NTP", note: "Network time" },
  { port: 143, proto: "TCP", name: "IMAP", note: "Mail access" },
  { port: 443, proto: "TCP", name: "HTTPS", note: "TLS web" },
  { port: 445, proto: "TCP", name: "SMB", note: "Windows file sharing" },
  { port: 465, proto: "TCP", name: "SMTPS", note: "SMTP over TLS (legacy)" },
  { port: 587, proto: "TCP", name: "SMTP submission", note: "Mail client → server (STARTTLS)" },
  { port: 631, proto: "TCP", name: "IPP", note: "Internet printing" },
  { port: 853, proto: "TCP", name: "DNS over TLS", note: "DoT" },
  { port: 873, proto: "TCP", name: "rsync", note: "File sync" },
  { port: 993, proto: "TCP", name: "IMAPS", note: "IMAP over TLS" },
  { port: 995, proto: "TCP", name: "POP3S", note: "POP3 over TLS" },
  { port: 1433, proto: "TCP", name: "MS SQL", note: "Microsoft SQL Server" },
  { port: 1521, proto: "TCP", name: "Oracle DB", note: "Oracle listener" },
  { port: 2049, proto: "both", name: "NFS", note: "Network file system" },
  { port: 2082, proto: "TCP", name: "cPanel HTTP", note: "Hosting panel" },
  { port: 2083, proto: "TCP", name: "cPanel HTTPS", note: "Hosting panel TLS" },
  { port: 2181, proto: "TCP", name: "ZooKeeper", note: "Coordination service" },
  { port: 2222, proto: "TCP", name: "Alt SSH", note: "Common alternate SSH" },
  { port: 2375, proto: "TCP", name: "Docker", note: "Unencrypted Docker API (avoid public)" },
  { port: 2376, proto: "TCP", name: "Docker TLS", note: "Docker API with TLS" },
  { port: 3000, proto: "TCP", name: "Dev servers", note: "Common Node/React dev default" },
  { port: 3306, proto: "TCP", name: "MySQL", note: "MySQL / MariaDB" },
  { port: 3389, proto: "TCP", name: "RDP", note: "Windows remote desktop" },
  { port: 4222, proto: "TCP", name: "NATS", note: "Messaging" },
  { port: 5000, proto: "TCP", name: "Flask / misc", note: "Common local dev / UPnP" },
  { port: 5432, proto: "TCP", name: "PostgreSQL", note: "Postgres default" },
  { port: 5672, proto: "TCP", name: "AMQP", note: "RabbitMQ" },
  { port: 5900, proto: "TCP", name: "VNC", note: "Remote framebuffer" },
  { port: 6379, proto: "TCP", name: "Redis", note: "In-memory data store" },
  { port: 8000, proto: "TCP", name: "HTTP alt", note: "Common dev / Django" },
  { port: 8080, proto: "TCP", name: "HTTP proxy", note: "Alternate HTTP / proxies" },
  { port: 8443, proto: "TCP", name: "HTTPS alt", note: "Common TLS alternate" },
  { port: 9200, proto: "TCP", name: "Elasticsearch", note: "HTTP API (legacy default)" },
  { port: 11211, proto: "both", name: "Memcached", note: "Cache" },
  { port: 27017, proto: "TCP", name: "MongoDB", note: "Mongo default" },
];
