export type GitignoreStackId =
  | "node"
  | "nextjs"
  | "python"
  | "rust"
  | "go"
  | "java"
  | "docker"
  | "terraform"
  | "macos"
  | "windows"
  | "linux"
  | "vscode"
  | "jetbrains";

export type GitignoreStack = {
  id: GitignoreStackId;
  label: string;
  lines: string[];
};

/** Curated ignore patterns merged when user picks stacks (offline “rules DB”). */
export const GITIGNORE_STACKS: GitignoreStack[] = [
  {
    id: "node",
    label: "Node / npm",
    lines: [
      "node_modules/",
      "npm-debug.log*",
      "yarn-debug.log*",
      "yarn-error.log*",
      "pnpm-debug.log*",
      ".npm",
      ".eslintcache",
      ".node_repl_history",
      "*.tsbuildinfo",
    ],
  },
  {
    id: "nextjs",
    label: "Next.js",
    lines: [
      ".next/",
      "out/",
      "build/",
      "dist/",
      ".vercel",
      "*.pem",
      ".env*.local",
    ],
  },
  {
    id: "python",
    label: "Python",
    lines: [
      "__pycache__/",
      "*.py[cod]",
      "*$py.class",
      ".Python",
      "venv/",
      ".venv/",
      "env/",
      ".env",
      "*.egg-info/",
      ".pytest_cache/",
      ".mypy_cache/",
      ".ruff_cache/",
    ],
  },
  {
    id: "rust",
    label: "Rust",
    lines: ["/target/", "**/*.rs.bk"],
  },
  {
    id: "go",
    label: "Go",
    lines: ["*.exe", "*.exe~", "*.dll", "*.so", "*.dylib", "*.test", "*.out", "vendor/"],
  },
  {
    id: "java",
    label: "Java / Gradle / Maven",
    lines: [
      "target/",
      "build/",
      ".gradle/",
      "*.class",
      "*.jar",
      "*.war",
      "*.ear",
      ".idea/",
      "*.iml",
    ],
  },
  {
    id: "docker",
    label: "Docker",
    lines: ["*.log", ".docker/"],
  },
  {
    id: "terraform",
    label: "Terraform",
    lines: [".terraform/", "*.tfstate", "*.tfstate.*", ".terraform.lock.hcl", "crash.log", "crash.*.log", "override.tf", "override.tf.json"],
  },
  {
    id: "macos",
    label: "macOS",
    lines: [".DS_Store", ".AppleDouble", ".LSOverride", "Icon\r", "._*", ".Spotlight-V100", ".Trashes"],
  },
  {
    id: "windows",
    label: "Windows",
    lines: ["Thumbs.db", "ehthumbs.db", "Desktop.ini", "$RECYCLE.BIN/"],
  },
  {
    id: "linux",
    label: "Linux",
    lines: ["*~", ".fuse_hidden*", ".directory", ".Trash-*"],
  },
  {
    id: "vscode",
    label: "VS Code",
    lines: [".vscode/*", "!.vscode/extensions.json", "!.vscode/settings.json"],
  },
  {
    id: "jetbrains",
    label: "JetBrains IDEs",
    lines: [".idea/", "*.iml", "*.ipr", "*.iws", "out/"],
  },
];

export function mergeGitignoreStacks(stackIds: GitignoreStackId[]): string {
  const picked = new Set(stackIds);
  const sections: string[] = [];
  const seenLine = new Set<string>();

  sections.push("# Generated by eProd — pick stacks and adjust as needed\n");

  for (const stack of GITIGNORE_STACKS) {
    if (!picked.has(stack.id)) continue;
    sections.push(`# --- ${stack.label} ---`);
    for (const line of stack.lines) {
      const norm = line.trim();
      if (!norm || seenLine.has(norm)) continue;
      seenLine.add(norm);
      sections.push(norm);
    }
    sections.push("");
  }

  return sections.join("\n").trimEnd() + "\n";
}
